server:
  port: 9296
  
spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/emee17/ms-one
          clone-on-start: true
