# Spring Boot configuration

spring: 
  datasource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=ms-emp
    username: postgres
    password: root
  # JPA properties
  jpa: 
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: "org.hibernate.dialect.PostgreSQL9Dialect"
    open-in-view: false
    generate-ddl: true
  application:
    name: EMPLOYEE-SERVICE
    
server:
  port: 9002 
  
  
# This is Common Configuration across all micro-service so This has been added in Config server
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
